print("Create your character")
name = input("What is the name of the character?")
age = input("How old is your charachter?")
strenghts = input("What is the strengths of the character?")
weaknesses = input("What is the characters weaknesses?")
print("Your characters name is", name)
print("Your character is", age, "years old")
print("Strengths", strenghts)
print("Weaknesses", weaknesses)
print(name, "says: Thank you for creating me")
